name: Metrics
on:
  schedule: [{cron: "0 2 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.general.svg
          base: header, activity, community, repositories
          plugin_languages: no
          plugin_lines: yes
          plugin_lines_sections: repositories
          config_timezone: Europe/Paris

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.calendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          config_timezone: Europe/Paris

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.followup.svg
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories
